### ISSUE TITLE
Getting Minified React error #130 in build version of application-version-6.7.0 

### ISSUE THREAD

**Issue by vineethasimon** [react-tags/react-tags#751] opened 2021-06-23 07:55 UTC
We are using react-tag-input in our application. We were getting  Minified React error #130 in build version of application. On analyzing, we identified that the issue is with latest version-6.7.0 of react-tag-input. Earlier version of 6.6.1 was not having this issue. In order fix the build issue,  we have locked the version of react-tag-input as 6.6.1 in package.json . Can you please check  the issue with latest version.

**Comment by ad1992** [comment] 2021-06-23 11:36
@vineethasimon what error are you getting? Looks like you have linked a wrong issue in the description.

**Comment by vineethasimon** [comment] 2021-06-28 04:40
> @vineethasimon what error are you getting? Looks like you have linked a wrong issue in the description.

hi @ad1992 ,
PFB actual error message received:

react-dom.production.min.js:209 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ol (react-dom.production.min.js:275)
    at react-dom.production.min.js:148
    at Ba (react-dom.production.min.js:173)
    at ms (react-dom.production.min.js:262)
    at ul (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at $s (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at zi (react-dom.production.min.js:122)

**Comment by kilimovich-aleksandr** [comment] 2021-06-29 07:42
I have the same issue, the full error message is on the screenshot 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33517184/123757412-a0eddf00-d8c6-11eb-9a5e-69d79901221e.png)

**Comment by ad1992** [comment] 2021-06-29 12:14
@vineethasimon @kilimovich-aleksandr can you share a CSB or stackblitz link for further debugging? 
It's working fine in the [demo](https://stackblitz.com/edit/react-tag-input-1nelrc) though.

**Comment by mattpetters** [comment] 2021-06-29 20:29
Yeah I also got this error on minified version 6.6.1 it looks like. Seems to only happen on minification. Spent several hours trying to recreate locally / in dev but it only happens on our staging environment due to the minified build.

**Comment by ad1992** [comment] 2021-06-29 20:37
Hmm ok so will have to check the prod build to investigate this

**Comment by mattpetters** [comment] 2021-06-29 20:42
> Hmm ok so will have to check the prod build to investigate this

@ad1992 I just did some more testing and found that forcing 6.6.1 solves the issue. I edited my above comment. However ^6.6.1 was causing issues so the latest version prod build is probably going to be where the issue is.

**Comment by ad1992** [comment] 2021-07-01 07:43
@mattpetters @vineethasimon I verified it with the prod build as well and it works fine. I think some issue related to peer dependency might be causing this error so please make sure you have installed all the peer dependencies including the dependencies of peer dependencies correctly as that's what has changed in the latest version.
<img width="1387" alt="Screenshot 2021-07-01 at 1 09 24 PM" src="https://user-images.githubusercontent.com/11256141/124085715-f6b0bb80-da6d-11eb-832c-53fcfe2f94f3.png">

**Comment by ad1992** [comment] 2021-07-12 14:37
closing this as this is not related to the library. feel free to reopen if you find the issue related to the library.

**Closed by ad1992** 2021-07-12 14:37 UTC
